name: Crystal CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: make build
    - name: Run tests
      run: make tests
    - name: Run linter
      run: make lint
