name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
    - uses: actions/checkout@v1
    - name: Check that it compiles
      run: make build
    - name: Run tests
      run: make tests
    - name: Run linter
      run: make lint
